### ISSUE TITLE
Error at compile time:  Undefined symbol: _swift_getFieldAt

### ISSUE THREAD

**Issue by manasv** [arturdev/Structify#2]
**OS:** macOS Catalina Developer Beta 5
**Xcode:** Xcode 10.3
**Swift:** 5.0 (The one bundled with Xcode 10.3)

I'm trying to use Structify in a small learning project, and have this issue when trying to compile (Same error with example project). It's something about Reflection dependency.

Thanks in advance!

<img width="1123" alt="Screen Shot 2019-08-09 at 3 45 32 PM" src="https://user-images.githubusercontent.com/474405/62810883-bda78080-babc-11e9-9211-38692db66a2e.png">

**Comment by arturdev** [comment]
@manasv I haven't optimized it for Xcode 10.3 yet

**Comment by manasv** [comment]
@arturdev Ok ok, hope it can get fixed in a future release, the project is amazing! :)

**Comment by arturdev** [comment]
Thanks! :)

**Comment by lubbo** [comment]
Hello!
Is this issue still open?
Still no support for Swift 5/Xcode 10.3+ ?

**Comment by manasv** [comment]
Will close because exist a kinda similar library from same developer, on more active development:

https://github.com/arturdev/Unrealm
